# Generated by Django 5.0.4 on 2024-05-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglistitem',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
